FROM nginx
ADD default.conf /etc/nginx/conf.d/default.conf

# nginx 이미지 생성 
# docker build --tag nginx:0.1 .
# nginx 컨테이너 생성 후 실행
# docker run --name nginx -p 80:80 --link gs-spring-boot-docker:gs-spring-boot-docker -d nginx:0.1